language: elixir
elixir:
  - 1.0.5
  - 1.1.0
  - 1.1.1
env:
  global:
    - MIX_ENV=test
before_install:
  - git submodule update --init --recursive
script:
  - "mix do deps.get, deps.compile, compile --warnings-as-errors, coveralls.travis"
notifications:
  email:
    - jonas.schmidt@gmx.com
