language: elixir
elixir:
  - 1.0.5
  - 1.1.0
  - 1.1.1
before_install:
  - git submodule update --init --recursive
before_script:
  - cd test/JSON-Schema-Test-Suite/remotes && python -m SimpleHTTPServer 1234 &
  - cd test/schemata && python -m SimpleHTTPServer &
notifications:
  email:
    - jonas.schmidt@gmx.com
