language: elixir
elixir:
  - 1.0.5
  - 1.1.0
  - 1.1.1
before_install:
  - git submodule update --init --recursive
script:
  - "MIX_ENV=test mix coveralls.travis"
notifications:
  email:
    - jonas.schmidt@gmx.com
